openapi: 3.0.3
info:
  title: Task Manager API
  version: 1.0.0
  description: An API for managing tasks, including CRUD operations, pagination, and flexible search.
paths:
  /tasks:
    post:
      summary: Retrieve all tasks with pagination and search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: Page number for pagination
                  default: 1
                pageSize:
                  type: integer
                  description: Number of tasks per page
                  default: 10
                searchQuery:
                  type: string
                  description: Search query to filter tasks by title, description, or status
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total:
                    type: integer
                    description: Total number of tasks
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request parameters"
  /tasks/create:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid task data"
  /tasks/details:
    post:
      summary: Retrieve a task by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the task to retrieve
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid task ID"
        '404':
          description: Task not found
  /tasks/{id}:
    put:
      summary: Update an existing task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid task data or ID"
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid task ID"
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          example: "Complete project documentation"
        description:
          type: string
          example: "Finalize and review all project-related documents"
        status:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T12:00:00Z"
    TaskCreateRequest:
      type: object
      required:
        - title
        - status
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 50
        description:
          type: string
          maxLength: 200
        status:
          type: boolean
    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 50
        description:
          type: string
          maxLength: 200
        status:
          type: boolean
